version: '3'
services:
  backend:
    build: ./docker/php
    volumes:
      - ./backend:/var/www/html/api
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/etc/conf.d/default.conf.nginx:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html/api
      - ./frontend/dist:/var/www/html
    depends_on:
      - backend